(function(){
  'use strict';
  const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>'US$ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
  const current=()=>typeof currentProject==='function'?currentProject():(window.projects||[])[0];
  function modal(id,title,subtitle,body){let el=$('#'+id);if(!el){el=document.createElement('div');el.id=id;el.className='masif-hu-modal';document.body.appendChild(el);}el.innerHTML=`<section class="masif-hu-card"><header class="masif-hu-head"><div><h2>${title}</h2><p>${subtitle}</p></div><button class="masif-hu-close" data-hu-close="${id}">×</button></header><div>${body}</div></section>`;el.classList.add('open');}
  function close(id){$('#'+id)?.classList.remove('open');}
  function download(name,text,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);}
  function projectProfile(){const p=current();return typeof getMasifProjectSummary==='function'?getMasifProjectSummary(p):{beneficiarios:p?.beneficiarios||0,viviendas:100,kmRed:4.82,inversion:98291.11,valvulas:14};}
  function addLocationFilter(){const host=$('.info-panel .info-top');if(!host||$('#masifLocationFilter'))return;host.insertAdjacentHTML('afterbegin',`<section class="masif-location-filter" id="masifLocationFilter"><h3>Filtrar agrupaciones por ubicación</h3><div class="masif-location-grid"><label>Departamento<select id="masifDept"></select></label><label>Provincia<select id="masifProv"></select></label><label class="wide">Distrito<select id="masifDist"></select></label></div><button id="masifApplyLocation" type="button">Aplicar filtro y centrar mapa</button></section>`);populateGeo();$('#masifDept').addEventListener('change',()=>populateGeo('department'));$('#masifProv').addEventListener('change',()=>populateGeo('province'));$('#masifApplyLocation').addEventListener('click',applyGeo);
  }
  function geoRows(){const list=typeof projects!=='undefined'?projects:[];return list.map(p=>({d:p.departamento||'Sin departamento',p:p.provincia||'Sin provincia',x:p.distrito||'Sin distrito',id:p.id}));}
  function fill(sel,vals,old){sel.innerHTML=[...new Set(vals)].map(v=>`<option>${esc(v)}</option>`).join('');if(old&&[...sel.options].some(o=>o.value===old))sel.value=old;}
  function populateGeo(level){const rows=geoRows(),d=$('#masifDept'),p=$('#masifProv'),x=$('#masifDist');if(!d)return;const cur=current();fill(d,rows.map(r=>r.d),level?d.value:cur?.departamento);const r1=rows.filter(r=>r.d===d.value);fill(p,r1.map(r=>r.p),level==='department'?null:(p.value||cur?.provincia));const r2=r1.filter(r=>r.p===p.value);fill(x,r2.map(r=>r.x),level?null:cur?.distrito);}
  function applyGeo(){const row=geoRows().find(r=>r.d===$('#masifDept').value&&r.p===$('#masifProv').value&&r.x===$('#masifDist').value);if(row&&typeof selectProject==='function')selectProject(row.id);else if(typeof leafletMap!=='undefined'&&leafletMap&&typeof getMasifProjectCenter==='function'){const g=getMasifProjectCenter({departamento:$('#masifDept').value,provincia:$('#masifProv').value,distrito:$('#masifDist').value});leafletMap.setView([g.lat,g.lng],g.zoom||14);}if(window.showToast)showToast('Filtro geográfico aplicado');}
  const vnrRows=()=>[{c:'VNR-PEAD-200',p:'Tubería PEAD 200 mm',u:'m',q:856.4,t:42.80},{c:'VNR-PEAD-160',p:'Tubería PEAD 160 mm',u:'m',q:420.2,t:34.60},{c:'VNR-VAL-SEC',p:'Válvula de seccionamiento',u:'und',q:8,t:1280},{c:'VNR-ACOM-DOM',p:'Acometida domiciliaria',u:'und',q:100,t:315}];
  function reportRows(){return vnrRows().map(r=>Object.assign({},r,{s:r.q*r.t}));}
  function openTechnical(){const rows=reportRows(),total=rows.reduce((s,r)=>s+r.s,0),p=current();modal('masifTechnicalModal','Informe técnico automático','Partidas VNR, cantidades GIS y tarifas referenciales Osinergmin.',`<div class="masif-hu-kpis"><div class="masif-hu-kpi"><span>Agrupación</span><b>${esc(p?.id)}</b></div><div class="masif-hu-kpi"><span>Partidas VNR</span><b>${rows.length}</b></div><div class="masif-hu-kpi"><span>KM de red</span><b>${projectProfile().kmRed}</b></div><div class="masif-hu-kpi"><span>Total calculado</span><b>${money(total)}</b></div></div>${table(['Código VNR','Partida','Unidad','Cantidad GIS','Tarifa Osinergmin','Subtotal'],rows.map(r=>[r.c,r.p,r.u,r.q,money(r.t),money(r.s)]))}<div class="masif-hu-toolbar" style="margin-top:14px"><button class="masif-hu-btn green" id="masifTechPdf">Generar PDF</button><button class="masif-hu-btn" id="masifTechWord">Generar Word</button></div>`);$('#masifTechPdf').onclick=()=>technicalPdf(rows,total);$('#masifTechWord').onclick=()=>technicalWord(rows,total);}
  function technicalPdf(rows,total){let J=window.jspdf?.jsPDF;try{J=J||parent.jspdf?.jsPDF}catch(e){}if(!J){window.print();return;}const p=current(),doc=new J({orientation:'landscape',unit:'pt',format:'a4'});doc.setFontSize(17);doc.text('INFORME TÉCNICO AUTOMÁTICO · MASIFICACIÓN',38,40);doc.setFontSize(10);doc.text(`Agrupación: ${p?.nombre||'-'} · ${p?.id||'-'} · ${p?.distrito||'-'}, ${p?.provincia||'-'}`,38,58);doc.text('Fuente: cantidades GIS y tarifas referenciales Osinergmin · Códigos VNR',38,73);if(doc.autoTable)doc.autoTable({startY:88,head:[['Código VNR','Partida','Unidad','Cantidad GIS','Tarifa','Subtotal']],body:rows.map(r=>[r.c,r.p,r.u,String(r.q),money(r.t),money(r.s)]),headStyles:{fillColor:[14,116,144]}});const y=(doc.lastAutoTable?.finalY||180)+24;doc.setFontSize(12);doc.text('Total valorizado: '+money(total),38,y);doc.text('Conclusión: metrados y valorización listos para revisión técnica y liquidación.',38,y+20);doc.save('informe_tecnico_vnr_masificacion.pdf');}
  function technicalWord(rows,total){const p=current(),trs=rows.map(r=>`<tr><td>${r.c}</td><td>${r.p}</td><td>${r.u}</td><td>${r.q}</td><td>${money(r.t)}</td><td>${money(r.s)}</td></tr>`).join('');download('informe_tecnico_vnr_masificacion.doc',`<html><meta charset="utf-8"><body><h1>Informe técnico automático · Masificación</h1><p><b>Agrupación:</b> ${esc(p?.nombre)} · ${esc(p?.id)}</p><p>Partidas VNR valorizadas con tarifas referenciales Osinergmin.</p><table border="1" cellspacing="0" cellpadding="6"><tr><th>Código VNR</th><th>Partida</th><th>Unidad</th><th>Cantidad GIS</th><th>Tarifa</th><th>Subtotal</th></tr>${trs}</table><h3>Total: ${money(total)}</h3><p>Conclusión: información integrada y lista para revisión del área técnica.</p></body></html>`,'application/msword');}
  function table(headers,rows){return `<div class="masif-hu-table-wrap"><table class="masif-hu-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  let liquidationRows=[['VNR-PEAD-200','TRON-001','856.40','GIS vinculado','Conforme'],['VNR-PEAD-160','RAM-002','420.20','GIS vinculado','Conforme'],['VNR-VAL-SEC','VAL-003','8','GIS vinculado','Conforme'],['VNR-ACOM-DOM','MZ-01','100','GIS vinculado','Por revisar']];
  function openLiquidation(){renderLiquidationModal();}
  function renderLiquidationModal(){const linked=liquidationRows.filter(r=>/vinculado/i.test(r[3])).length;modal('masifLiquidationModal','Automatización de liquidaciones','Carga del modelo Excel y enlace de partidas con objetos espaciales GIS.',`<div class="masif-hu-toolbar"><label>Modelo de liquidación<input id="masifLiqFile" type="file" accept=".xlsx,.xls,.csv"></label><button class="masif-hu-btn alt" id="masifLiqTemplate">Descargar formato</button><button class="masif-hu-btn green" id="masifLiqExport">Generar cuadro integrado</button></div><div class="masif-hu-kpis"><div class="masif-hu-kpi"><span>Filas importadas</span><b>${liquidationRows.length}</b></div><div class="masif-hu-kpi"><span>Vinculadas al GIS</span><b>${linked}</b></div><div class="masif-hu-kpi"><span>Observadas</span><b>${liquidationRows.length-linked}</b></div><div class="masif-hu-kpi"><span>Estado</span><b>${linked===liquidationRows.length?'Conforme':'En revisión'}</b></div></div>${table(['Código VNR','Objeto GIS','Cantidad','Vinculación espacial','Validación'],liquidationRows.map(r=>[r[0],r[1],r[2],`<span class="${/vinculado/i.test(r[3])?'masif-link-ok':'masif-link-warn'}">${r[3]}</span>`,r[4]]))}`);$('#masifLiqTemplate').onclick=()=>download('formato_liquidacion_masificacion.csv','Codigo VNR,Objeto GIS,Cantidad,Unidad,Estado\nVNR-PEAD-200,TRON-001,0,m,Pendiente');$('#masifLiqExport').onclick=()=>download('liquidacion_integrada_gis.csv','Codigo VNR,Objeto GIS,Cantidad,Vinculacion,Validacion\n'+liquidationRows.map(r=>r.join(',')).join('\n'));$('#masifLiqFile').onchange=readLiquidation;}
  function readLiquidation(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{try{let rows=[];if(/\.csv$/i.test(file.name)){rows=String(ev.target.result).split(/\r?\n/).slice(1).filter(Boolean).map(x=>x.split(',').slice(0,5));}else{let X=window.XLSX;try{X=X||parent.XLSX}catch(err){}if(X){const wb=X.read(ev.target.result,{type:'array'});rows=X.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1}).slice(1).filter(r=>r.length).map(r=>[r[0]||'',r[1]||'',r[2]||0,r[1]?'GIS vinculado':'Sin vínculo',r[1]?'Conforme':'Observado']);}}if(rows.length)liquidationRows=rows;renderLiquidationModal();}catch(err){if(window.showToast)showToast('No se pudo leer el formato de liquidación');}};if(/\.csv$/i.test(file.name))reader.readAsText(file);else reader.readAsArrayBuffer(file);}
  function potentialContext(){
    const selected=(typeof activeSelectionRecords!=='undefined'&&activeSelectionRecords.length)?activeSelectionRecords:
      ((typeof activeAreaRecords!=='undefined'&&activeAreaRecords.length)?activeAreaRecords:[]);
    const p=current(),profile=projectProfile();
    const base=selected.length?selected:[];
    const predios=base.length?base.reduce((sum,r)=>sum+Number(r.hogares||r.predios||r.beneficiarios||1),0):Math.max(Number(profile.viviendas||p?.beneficiarios||0),1);
    const rows=base.length?base.map((r,i)=>{
      const count=Math.max(1,Number(r.hogares||r.predios||r.beneficiarios||1));
      const covered=Math.max(0,Math.round(count*(String(r.estadoInstalacion||'').toLowerCase().includes('conect')?.92:.72)));
      const concession=Math.max(0,Math.round(count*.24));
      return [r.manzana||r.suministro||('SELECCIÓN-'+(i+1)),count,covered,concession,Math.max(covered,covered+concession-Math.round(count*.12))];
    }):Array.from({length:Math.min(4,Math.max(1,Math.ceil(predios/30)))},(_,i)=>{
      const count=i===Math.ceil(predios/30)-1?Math.max(1,predios-(i*30)):Math.min(30,predios);
      const covered=Math.round(count*.78),concession=Math.round(count*.24);
      return ['MZ-'+String(i+1).padStart(2,'0'),count,covered,concession,Math.max(covered,covered+concession-Math.round(count*.12))];
    });
    return {rows,predios,source:base.length?(typeof activeAreaRecords!=='undefined'&&activeAreaRecords.length?'Área dibujada':'Objetos seleccionados'):'Proyecto '+(p?.nombre||p?.id||'actual')};
  }
  function openPotential(){const ctx=potentialContext(),res=Math.round(ctx.predios*.82),con=Math.round(ctx.predios*.24),potential=ctx.rows.reduce((sum,r)=>sum+Number(r[4]||0),0);modal('masifPotentialModal','Identificación de beneficiarios potenciales','Cálculo dinámico según '+ctx.source+'.',`<div class="masif-hu-kpis"><div class="masif-hu-kpi"><span>Predios analizados</span><b>${ctx.predios}</b></div><div class="masif-hu-kpi"><span>Residenciales</span><b>${res}</b></div><div class="masif-hu-kpi"><span>Proyección concesionario</span><b>${con}</b></div><div class="masif-hu-kpi"><span>Potenciales únicos</span><b>${potential}</b></div></div>${table(['Manzana / selección','Predios','Con cobertura FISE','Proyección concesionario','Beneficiarios potenciales'],ctx.rows)}<p style="color:#aebbd3;font-size:10px;line-height:1.5">Fuente activa: ${esc(ctx.source)}. El resultado se recalcula al seleccionar un proyecto, un objeto, un círculo o un polígono.</p><div class="masif-hu-toolbar"><button class="masif-hu-btn green" id="masifPotentialExport">Exportar potencial de abastecimiento</button></div>`);$('#masifPotentialExport').onclick=()=>download('potencial_abastecimiento_masificacion.csv','Manzana o seleccion,Predios,Cobertura FISE,Proyeccion concesionario,Beneficiarios potenciales\n'+ctx.rows.map(r=>r.join(',')).join('\n'));}
  const phases=['Planificación','Registro de la agrupación','Evaluación GIS','Validación técnica','Validación concesionaria','Programación de obra','Ejecución de red','Liquidación','Monitoreo'];
  function openTrace(){const rows=phases.map((n,i)=>`<div class="masif-phase ${i<5?'done':i===5?'current':''}"><i>${i<5?'✓':i+1}</i><div><b>${i+1}. ${n}</b><span>${i<5?'Completada · '+String(10+i).padStart(2,'0')+'/07/2026':i===5?'Fase actual · Responsable: Operaciones':'Pendiente'}</span></div></div>`).join('');modal('masifTraceModal','Trazabilidad del expediente','Flujo de nueve fases y auditoría entre zonas concesionadas y no concesionadas.',`<div class="masif-hu-toolbar"><label>Tipo de zona<select id="masifZone"><option>Zona concesionada</option><option>Zona no concesionada</option></select></label><label>Expediente<input value="${esc(current()?.id)}" readonly></label><button class="masif-hu-btn alt" id="masifTraceExport">Exportar auditoría</button></div><div class="masif-trace">${rows}</div>${table(['Fecha y hora','Usuario','Estado anterior','Nuevo estado','Zona'],[['15/07/2026 09:15','Equipo GIS','Registro','Evaluación GIS','Concesionada'],['16/07/2026 11:40','Analista técnico','Evaluación GIS','Validación técnica','Concesionada'],['17/07/2026 16:05','Concesionaria','Validación técnica','Validación concesionaria','Concesionada'],['20/07/2026 08:30','Operaciones','Validación concesionaria','Programación de obra','Concesionada']])}`);$('#masifZone').onchange=e=>window.showToast&&showToast('Transición de análisis: '+e.target.value);$('#masifTraceExport').onclick=()=>download('auditoria_trazabilidad_9_fases.csv','Fase,Estado,Responsable\n'+phases.map((p,i)=>`${i+1} - ${p},${i<5?'Completada':i===5?'Actual':'Pendiente'},${i===5?'Operaciones':'Equipo responsable'}`).join('\n'));}
  function addActions(){const exportBtn=$('#exportExcelBtn');if(!exportBtn)return;if(!$('#masifHuActions'))exportBtn.insertAdjacentHTML('afterend',`<div class="masif-hu-actions" id="masifHuActions"><button type="button" id="masifPotentialBtn">Beneficiarios potenciales</button><button type="button" id="masifTraceBtn">Trazabilidad · 9 fases</button></div>`);const potential=$('#masifPotentialBtn'),trace=$('#masifTraceBtn');if(potential)potential.onclick=openPotential;if(trace)trace.onclick=openTrace;}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-hu-close]');if(b)close(b.dataset.huClose);if(e.target.classList.contains('masif-hu-modal'))e.target.classList.remove('open');});
  window.openMasifTechnicalHu=openTechnical;
  window.openMasifLiquidationHu=openLiquidation;
  function applyProjectTerminology(){
    const replacements=[
      ['#infoName','AGRUPACIÓN SAUNA 1','PROYECTO SAUNA 1'],
      ['#modalTitle','Crear agrupación','Crear proyecto']
    ];
    replacements.forEach(([selector,from,to])=>{const el=$(selector);if(el&&el.textContent.trim()===from)el.textContent=to;});
    const modal=$('#projectModal');
    if(modal){
      const walker=document.createTreeWalker(modal,NodeFilter.SHOW_TEXT);
      const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
      nodes.forEach(node=>{node.nodeValue=node.nodeValue.replace(/agrupaciones/gi,'proyectos').replace(/agrupación/gi,'proyecto');});
    }
  }
  function init(){applyProjectTerminology();addLocationFilter();addActions();const p=current();if(p&&typeof renderMasifProjectDetail==='function')renderMasifProjectDetail(p,projectProfile());}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();
